//! Tauri IPC command registration.

use super::{__cmd__update_tray_menu, __tauri_command_name_update_tray_menu, update_tray_menu};
use crate::commands;

pub(super) fn register(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {
    builder.invoke_handler(tauri::generate_handler![
        commands::get_providers,
        commands::get_current_provider,
        commands::add_provider,
        commands::update_provider,
        commands::delete_provider,
        commands::remove_provider_from_live_config,
        commands::switch_provider,
        commands::verify_provider_key,
        commands::import_default_config,
        commands::get_claude_desktop_status,
        commands::get_claude_desktop_default_routes,
        commands::import_claude_desktop_providers_from_claude,
        commands::ensure_claude_desktop_official_provider,
        commands::get_claude_config_status,
        commands::get_config_status,
        commands::get_claude_code_config_path,
        commands::get_config_dir,
        commands::open_config_folder,
        commands::pick_directory,
        commands::open_external,
        commands::get_build_info,
        commands::get_init_error,
        commands::get_migration_result,
        commands::get_skills_migration_result,
        commands::get_app_config_path,
        commands::open_app_config_folder,
        commands::get_claude_common_config_snippet,
        commands::set_claude_common_config_snippet,
        commands::get_common_config_snippet,
        commands::set_common_config_snippet,
        commands::extract_common_config_snippet,
        commands::read_live_provider_settings,
        commands::get_settings,
        commands::save_settings,
        commands::get_rectifier_config,
        commands::set_rectifier_config,
        commands::get_optimizer_config,
        commands::set_optimizer_config,
        commands::get_copilot_optimizer_config,
        commands::set_copilot_optimizer_config,
        commands::get_log_config,
        commands::set_log_config,
        commands::restart_app,
        commands::install_update_and_restart,
        commands::check_for_updates,
        commands::is_portable_mode,
        commands::copy_text_to_clipboard,
        commands::get_claude_plugin_status,
        commands::read_claude_plugin_config,
        commands::apply_claude_plugin_config,
        commands::is_claude_plugin_applied,
        commands::apply_claude_onboarding_skip,
        commands::clear_claude_onboarding_skip,
        // Claude MCP management
        commands::get_claude_mcp_status,
        commands::read_claude_mcp_config,
        commands::upsert_claude_mcp_server,
        commands::delete_claude_mcp_server,
        commands::validate_mcp_command,
        commands::probe_project_mcp_runtime,
        // usage query
        commands::queryProviderUsage,
        commands::testUsageScript,
        commands::confirm_usage_script_host,
        // subscription quota
        commands::get_subscription_quota,
        commands::get_codex_oauth_quota,
        commands::get_codex_oauth_models,
        commands::subscription_list_accounts,
        commands::subscription_list_project_routes,
        commands::subscription_save_project_route,
        commands::subscription_recommend_project_account,
        commands::get_coding_plan_quota,
        commands::get_balance,
        // New MCP via config.json (SSOT)
        commands::get_mcp_config,
        commands::upsert_mcp_server_in_config,
        commands::delete_mcp_server_in_config,
        commands::set_mcp_enabled,
        // Unified MCP management
        commands::get_mcp_servers,
        commands::upsert_mcp_server,
        commands::delete_mcp_server,
        commands::toggle_mcp_app,
        commands::import_mcp_from_apps,
        // MCP Registry discovery
        commands::search_mcp_registry,
        commands::get_mcp_registry_server,
        commands::install_mcp_from_registry,
        // Smithery Registry discovery
        commands::search_smithery_servers,
        commands::get_smithery_server_detail,
        commands::install_mcp_from_smithery,
        // MCP connection test
        commands::test_mcp_connection,
        // Prompt management
        commands::get_prompts,
        commands::upsert_prompt,
        commands::delete_prompt,
        commands::enable_prompt,
        commands::preview_prompt_activation,
        commands::get_dry_run_mode,
        commands::set_dry_run_mode,
        commands::import_prompt_from_file,
        commands::get_current_prompt_file_content,
        // Prompt bridge
        commands::bridge_prompt,
        commands::get_bridgeable_prompts,
        commands::push_bridge_changes,
        commands::unlink_bridge,
        commands::preview_bridge,
        commands::get_bridge_auto_push,
        commands::set_bridge_auto_push,
        // Config convert wizard (F3)
        commands::detect_convert_sources,
        commands::preview_convert,
        commands::apply_convert,
        // model list fetch (OpenAI-compatible /v1/models)
        commands::fetch_models_for_config,
        // ours: endpoint speed test + custom endpoint management
        commands::test_api_endpoints,
        commands::get_custom_endpoints,
        commands::add_custom_endpoint,
        commands::remove_custom_endpoint,
        commands::update_endpoint_last_used,
        // app_config_dir override via Store
        commands::get_app_config_dir_override,
        commands::set_app_config_dir_override,
        // provider sort order management
        commands::update_providers_sort_order,
        // theirs: config import/export and dialogs
        commands::export_config_to_file,
        commands::import_config_from_file,
        commands::webdav_test_connection,
        commands::webdav_sync_upload,
        commands::webdav_sync_download,
        commands::webdav_sync_save_settings,
        commands::webdav_sync_fetch_remote_info,
        commands::s3_test_connection,
        commands::s3_sync_upload,
        commands::s3_sync_download,
        commands::s3_sync_save_settings,
        commands::s3_sync_fetch_remote_info,
        commands::gist_sync_test_connection,
        commands::gist_sync_upload,
        commands::gist_sync_download,
        commands::gist_sync_save_pat,
        commands::gist_sync_clear,
        commands::gist_sync_is_configured,
        commands::save_file_dialog,
        commands::open_file_dialog,
        commands::open_zip_file_dialog,
        commands::create_db_backup,
        commands::list_db_backups,
        commands::restore_db_backup,
        commands::rename_db_backup,
        commands::delete_db_backup,
        commands::sync_current_providers_live,
        // Deep link import
        commands::parse_deeplink,
        commands::merge_deeplink_config,
        commands::import_from_deeplink,
        commands::import_from_deeplink_unified,
        update_tray_menu,
        // Environment variable management
        commands::check_env_conflicts,
        commands::delete_env_vars,
        commands::restore_env_backup,
        // Skill management (v3.10.0+ unified)
        commands::get_installed_skills,
        commands::get_skill_backups,
        commands::delete_skill_backup,
        commands::install_skill_unified,
        commands::uninstall_skill_unified,
        commands::restore_skill_backup,
        commands::toggle_skill_app,
        commands::batch_toggle_skill_app,
        commands::scan_unmanaged_skills,
        commands::import_skills_from_apps,
        commands::discover_available_skills,
        commands::check_skill_updates,
        commands::update_skill,
        commands::migrate_skill_storage,
        commands::resync_all_skills,
        commands::search_skills_sh,
        commands::get_skills_sh_leaderboard,
        commands::search_clawhub,
        commands::batch_get_clawhub_stats,
        commands::install_clawhub_skill,
        commands::search_modelscope,
        // Skill management (legacy API compatibility)
        commands::get_skills,
        commands::get_skills_for_app,
        commands::install_skill,
        commands::install_skill_for_app,
        commands::uninstall_skill,
        commands::uninstall_skill_for_app,
        commands::get_skill_repos,
        commands::add_skill_repo,
        commands::remove_skill_repo,
        commands::toggle_skill_repo,
        commands::install_skills_from_zip,
        // Auto launch
        commands::set_auto_launch,
        commands::get_auto_launch_status,
        // Proxy server management
        commands::start_proxy_server,
        commands::stop_proxy_server,
        commands::stop_proxy_with_restore,
        commands::get_proxy_takeover_status,
        commands::set_proxy_takeover_for_app,
        commands::get_proxy_status,
        commands::get_proxy_config,
        commands::update_proxy_config,
        // Global & Per-App Config
        commands::get_global_proxy_config,
        commands::update_global_proxy_config,
        commands::get_proxy_config_for_app,
        commands::update_proxy_config_for_app,
        commands::get_default_cost_multiplier,
        commands::set_default_cost_multiplier,
        commands::get_pricing_model_source,
        commands::set_pricing_model_source,
        commands::is_proxy_running,
        commands::is_live_takeover_active,
        commands::switch_proxy_provider,
        // QuickStart transactional workflow
        commands::quick_start_apply,
        commands::quick_start_get_operation,
        commands::quick_start_list_recoverable,
        commands::quick_start_list_recent,
        commands::quick_start_get_events,
        commands::quick_start_rollback,
        // Proxy failover commands
        commands::get_provider_health,
        commands::reset_circuit_breaker,
        commands::get_circuit_breaker_config,
        commands::update_circuit_breaker_config,
        commands::get_circuit_breaker_stats,
        // Failover queue management
        commands::get_failover_queue,
        commands::get_available_providers_for_failover,
        commands::add_to_failover_queue,
        commands::remove_from_failover_queue,
        commands::get_auto_failover_enabled,
        commands::set_auto_failover_enabled,
        // Usage statistics
        commands::get_usage_summary,
        commands::get_usage_summary_by_app,
        commands::get_usage_trends,
        commands::get_provider_stats,
        commands::get_model_stats,
        commands::get_request_logs,
        commands::get_request_detail,
        commands::get_model_pricing,
        commands::update_model_pricing,
        commands::delete_model_pricing,
        commands::check_provider_limits,
        // Session usage sync
        commands::sync_session_usage,
        commands::get_usage_data_sources,
        // Stream health check
        commands::stream_check_provider,
        commands::stream_check_all_providers,
        commands::get_stream_check_config,
        commands::save_stream_check_config,
        // Session manager
        commands::list_sessions,
        commands::get_session_messages,
        commands::delete_session,
        commands::delete_sessions,
        commands::launch_session_terminal,
        commands::get_tool_versions,
        commands::run_tool_lifecycle_action,
        commands::probe_tool_installations,
        // Provider terminal
        commands::open_provider_terminal,
        // Universal Provider management
        commands::get_universal_providers,
        commands::get_universal_provider,
        commands::upsert_universal_provider,
        commands::delete_universal_provider,
        commands::sync_universal_provider,
        // OpenCode specific
        commands::import_opencode_providers_from_live,
        commands::get_opencode_live_provider_ids,
        // OpenClaw specific
        commands::import_openclaw_providers_from_live,
        commands::get_openclaw_live_provider_ids,
        commands::get_openclaw_live_provider,
        commands::scan_openclaw_config_health,
        commands::get_openclaw_default_model,
        commands::set_openclaw_default_model,
        commands::get_openclaw_model_catalog,
        commands::set_openclaw_model_catalog,
        commands::get_openclaw_agents_defaults,
        commands::set_openclaw_agents_defaults,
        commands::get_openclaw_env,
        commands::set_openclaw_env,
        commands::get_openclaw_tools,
        commands::set_openclaw_tools,
        // Hermes specific
        commands::import_hermes_providers_from_live,
        commands::get_hermes_live_provider_ids,
        commands::get_hermes_live_provider,
        commands::get_hermes_model_config,
        commands::open_hermes_web_ui,
        commands::launch_hermes_dashboard,
        commands::get_hermes_memory,
        commands::set_hermes_memory,
        commands::get_hermes_memory_limits,
        commands::set_hermes_memory_enabled,
        // Global upstream proxy
        commands::get_global_proxy_url,
        commands::set_global_proxy_url,
        commands::test_proxy_url,
        commands::get_upstream_proxy_status,
        commands::scan_local_proxies,
        // Window theme control
        commands::set_window_theme,
        // Generic managed auth commands
        commands::auth_start_login,
        commands::auth_poll_for_account,
        commands::auth_list_accounts,
        commands::auth_get_status,
        commands::auth_remove_account,
        commands::auth_set_default_account,
        commands::auth_logout,
        commands::get_local_cli_auth_status,
        // OpenSunstar product-account session (token-free IPC only)
        commands::product_auth_get_session,
        commands::product_auth_login,
        commands::product_auth_cancel_login,
        commands::product_auth_logout,
        commands::product_team_create_organization,
        commands::product_team_accept_invite,
        commands::product_team_get_overview,
        commands::product_team_list_members,
        commands::product_team_list_invites,
        commands::product_team_invite_member,
        commands::product_team_remove_member,
        // D16 Team Key commands
        commands::team_key_sync,
        commands::team_key_renew,
        commands::team_key_list,
        commands::team_key_status,
        // Copilot OAuth commands (multi-account support)
        commands::copilot_start_device_flow,
        commands::copilot_poll_for_auth,
        commands::copilot_poll_for_account,
        commands::copilot_list_accounts,
        commands::copilot_remove_account,
        commands::copilot_set_default_account,
        commands::copilot_get_auth_status,
        commands::copilot_logout,
        commands::copilot_is_authenticated,
        commands::copilot_get_token,
        commands::copilot_get_token_for_account,
        commands::copilot_get_models,
        commands::copilot_get_models_for_account,
        commands::copilot_get_usage,
        commands::copilot_get_usage_for_account,
        // OMO commands
        commands::read_omo_local_file,
        commands::get_current_omo_provider_id,
        commands::disable_current_omo,
        commands::read_omo_slim_local_file,
        commands::get_current_omo_slim_provider_id,
        commands::disable_current_omo_slim,
        // lightweight mode (for testing or low-resource environments)
        commands::enter_lightweight_mode,
        commands::exit_lightweight_mode,
        commands::is_lightweight_mode,
        // Project board metrics (移植自 AIControls v0.2.1)
        commands::count_project_code_lines,
        commands::read_package_version,
        commands::detect_project_git_info,
        commands::git_commit_count_last_n_days,
        commands::git_weekly_commit_counts,
        commands::git_contributors,
        commands::reveal_path_in_folder,
        // AI insight commands (项目看板 AI 能力 Phase 1)
        commands::get_ai_insight,
        commands::get_ai_health_score,
        commands::get_ai_cost_summary,
        commands::get_ai_roi_report,
        commands::estimate_project_progress,
        // AI insight commands Phase 2 (风险分析 + 自然语言查询)
        commands::get_ai_risk_analysis,
        commands::query_projects_nl,
        // AI insight commands Phase 3 (智能周报)
        commands::generate_weekly_report,
        // AI insight commands F-P2-1 (Agent 配置就绪度 + 反馈闭环)
        commands::get_agent_readiness_score,
        commands::scan_project_effective_state,
        commands::repair_asset_drift,
        commands::repair_project_drift,
        commands::preview_repair_project_drift,
        commands::submit_insight_feedback,
        commands::submit_ai_query_feedback,
        // Session & usage export
        commands::export_session,
        commands::export_usage,
        // Onboarding wizard
        commands::scan_environment,
        commands::complete_onboarding,
        commands::is_onboarding_needed,
        // Project-level config isolation (方案 E)
        commands::get_all_projects,
        commands::get_project,
        commands::get_project_by_path,
        commands::upsert_project,
        commands::delete_project,
        commands::update_project_board_metadata,
        // AI insight provider settings (Keychain)
        commands::get_ai_insight_provider_settings,
        commands::save_ai_insight_provider_choice,
        commands::save_ai_insight_deepseek_key,
        commands::save_ai_insight_glm_settings,
        commands::save_ai_insight_custom_settings,
        commands::build_ai_insight_provider_config,
        commands::get_project_mcp_servers,
        commands::link_project_mcp_server,
        commands::unlink_project_mcp_server,
        commands::set_project_mcp_servers,
        commands::get_project_skills,
        commands::link_project_skill,
        commands::unlink_project_skill,
        commands::set_project_skills,
        commands::get_project_prompts,
        commands::link_project_prompt,
        commands::unlink_project_prompt,
        commands::set_project_prompts,
        commands::get_project_context_files,
        commands::set_project_target_app,
        commands::list_project_blueprints,
        commands::get_project_blueprint,
        commands::preview_apply_project_blueprint,
        commands::apply_project_blueprint,
        commands::export_project_baseline_snapshot,
        commands::list_workflow_modules_cmd,
        commands::list_workflow_presets_cmd,
        commands::get_workflow_preset_cmd,
        commands::scan_project_specs_workflow_cmd,
        commands::validate_workflow_stage_gate_cmd,
        commands::preview_project_workflow_profile_export_cmd,
        commands::export_project_workflow_profile_cmd,
        commands::preview_flow_config_export_cmd,
        commands::export_flow_config_cmd,
        commands::read_orchestration_log_cmd,
        commands::restore_latest_orchestration_receipt_cmd,
        commands::build_stage_graph_cmd,
        commands::compose_recipe_cmd,
        commands::preview_recipe_cmd,
        commands::export_recipe_cmd,
        commands::list_saved_recipes_cmd,
        commands::read_saved_recipe_cmd,
        commands::load_saved_recipe_cmd,
        commands::delete_saved_recipe_cmd,
        commands::install_recipe_cmd,
        commands::preview_recipe_install_plan_cmd,
        commands::list_design_templates_cmd,
        commands::list_design_system_packages_cmd,
        commands::get_design_system_package_contract_cmd,
        commands::get_design_system_package_detail_cmd,
        commands::get_design_template_cmd,
        commands::compose_design_contract_cmd,
        commands::preview_design_md_cmd,
        commands::preview_dtchg_json_cmd,
        commands::preview_design_export_plan_cmd,
        commands::export_design_contract_cmd,
        commands::preview_design_install_plan_cmd,
        commands::install_design_contract_cmd,
        commands::verify_design_system_manifest_cmd,
        commands::import_design_from_file_cmd,
        commands::import_design_from_url_cmd,
        commands::sdd_list_descriptors_cmd,
        commands::sdd_detect_project_cmd,
        commands::sdd_detect_all_projects_cmd,
        commands::sdd_get_detection_results_cmd,
        commands::sdd_get_all_saved_detections_cmd,
        commands::sdd_recommend_preset_cmd,
        commands::get_project_asset_links,
        commands::link_project_asset,
        commands::unlink_project_asset,
        commands::set_project_assets,
        commands::get_project_all_asset_counts,
        commands::list_extended_project_asset_types,
        commands::get_project_asset_health_cmd,
        commands::plan_project_asset_health_cmd,
        commands::apply_project_asset_health_plan_cmd,
        commands::rollback_project_asset_health_receipt_cmd,
        commands::register_asset_revision_cmd,
        commands::list_project_environment_snapshots,
        commands::create_project_environment_snapshot,
        commands::delete_project_environment_snapshot,
        commands::preview_project_environment_snapshot_apply,
        commands::apply_project_environment_snapshot,
        commands::rollback_project_environment_snapshot,
        // Commands & Hooks (v0.6.5 M1)
        commands::get_all_commands,
        commands::upsert_command,
        commands::delete_command,
        commands::toggle_command_app,
        commands::get_all_agents,
        commands::upsert_agent,
        commands::delete_agent,
        commands::toggle_agent_app,
        commands::preview_agent_codex_toml,
        commands::get_all_hooks,
        commands::upsert_hook,
        commands::delete_hook,
        commands::toggle_hook_app,
        commands::sync_hooks,
        // Ignore rules (F4)
        commands::get_all_ignore_rules,
        commands::upsert_ignore_rule,
        commands::delete_ignore_rule,
        commands::toggle_ignore_app,
        commands::import_ignore_from_gitignore,
        commands::sync_ignore_rules,
        // Tool permissions (F5)
        commands::get_all_tool_permissions,
        commands::upsert_tool_permission,
        commands::delete_tool_permission,
        commands::toggle_permission_app,
        commands::sync_tool_permissions,
        commands::get_permission_presets,
        commands::apply_permission_preset,
        // Project Wiki Baseline
        commands::scan_project_wiki_cmd,
        commands::inventory_project_wiki_cmd,
        commands::run_project_wiki_lint_cmd,
        commands::preview_project_wiki_init_cmd,
        commands::init_project_wiki_cmd,
        commands::map_project_wiki_changed_files_cmd,
    ])
}
