//! Project-level machine-readable artifacts for CLI agents (P0-4 / P0-1).

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::str::FromStr;

use serde::{Deserialize, Serialize};

use crate::ai::agent_readiness::{readiness_item_is_actionable_gap, AGENT_READINESS_MAX_SCORE};
use crate::ai::types::{AgentReadinessItem, AgentReadinessResult};
use crate::app_config::AppType;
use crate::config::write_text_file;
use crate::database::Database;
use crate::error::AppError;
use crate::services::skill::SkillService;

const OPENSUNSTAR_DIR: &str = ".opensunstar";
const ATL_COMPAT_DIR: &str = ".atl";
const HINTS_FILENAME: &str = "agent-context-hints.md";
const REGISTRY_FILENAME: &str = "skill-registry.md";
const BASELINE_SNAPSHOT_FILENAME: &str = "baseline-snapshot.json";
const BASELINE_SNAPSHOT_VERSION: u32 = 1;

/// 项目工作区目录是否仍可访问（用于跳过失效路径上的文件导出）
pub fn project_workspace_exists(project_path: &str) -> bool {
    Path::new(project_path).is_dir()
}

#[derive(Debug, Clone)]
struct RegistryRow {
    name: String,
    description: String,
    scope: &'static str,
    path: PathBuf,
}

/// 就绪度评估后写回 agent 产物；工作区路径已失效时静默跳过（常见于项目搬迁后 DB 未更新）
pub fn export_readiness_artifacts(
    db: &Database,
    project_path: &str,
    target_app: Option<&str>,
    result: &AgentReadinessResult,
) {
    if !project_workspace_exists(project_path) {
        log::debug!(
            "跳过 agent-context-hints / skill-registry 导出：项目路径不可用 ({project_path})"
        );
        return;
    }
    if let Err(e) = export_agent_context_hints(project_path, result) {
        log::warn!("导出 agent-context-hints 失败: {e}");
    }
    if let Err(e) = export_skill_registry(db, project_path, target_app) {
        log::warn!("导出 skill-registry 失败: {e}");
    }
}

/// Write `.opensunstar/agent-context-hints.md` from readiness scoring output.
pub fn export_agent_context_hints(
    project_path: &str,
    result: &AgentReadinessResult,
) -> Result<PathBuf, AppError> {
    let root = PathBuf::from(project_path);
    if !root.is_dir() {
        return Err(AppError::Message(format!(
            "项目路径不存在或不是目录: {project_path}"
        )));
    }

    let out_dir = root.join(OPENSUNSTAR_DIR);
    let out_path = out_dir.join(HINTS_FILENAME);
    let body = render_agent_context_hints(result);
    write_text_file(&out_path, &body)?;
    Ok(out_path)
}

fn render_agent_context_hints(result: &AgentReadinessResult) -> String {
    let evaluated = result
        .evaluated_at
        .map(|ts| ts.to_string())
        .unwrap_or_else(|| "unknown".to_string());
    let target = result.target_app.as_deref().unwrap_or("claude").to_string();

    let mut lines = vec![
        "# OpenSunstar Agent Context Hints".to_string(),
        String::new(),
        "> Auto-generated by OpenSunstar. Do not edit manually — changes will be overwritten."
            .to_string(),
        String::new(),
        format!(
            "- **Score**: {}/{}",
            result.score,
            result.max_score.max(AGENT_READINESS_MAX_SCORE)
        ),
        format!("- **Target CLI**: {target}"),
        format!("- **Evaluated at (unix)**: {evaluated}"),
        String::new(),
        "## Gaps and status".to_string(),
        String::new(),
    ];

    for item in &result.details {
        lines.push(format!(
            "- **{}** ({}/{}): {} [{}]",
            item.label,
            item.score,
            item.weight,
            item.detail,
            item.status.as_deref().unwrap_or("unknown")
        ));
        if let Some(ref eff) = item.effective_state {
            if eff != "effective" && eff != "not_applicable" {
                if let Some(ref detail) = item.effective_detail {
                    lines.push(format!("  - Effective state: {eff} — {detail}"));
                }
            }
        }
    }

    if let Some(ref suggestion) = result.llm_suggestion {
        if !suggestion.trim().is_empty() {
            lines.push(String::new());
            lines.push("## Suggestions".to_string());
            lines.push(String::new());
            lines.push(suggestion.trim().to_string());
        }
    }

    lines.push(String::new());
    lines.push("## Recommended next steps".to_string());
    lines.push(String::new());
    let actionable_gaps: Vec<&AgentReadinessItem> = result
        .details
        .iter()
        .filter(|item| readiness_item_is_actionable_gap(item))
        .collect();
    for item in &actionable_gaps {
        if let Some(action) = readiness_action_hint(item) {
            lines.push(format!("- {action}"));
        }
    }

    if actionable_gaps.is_empty() {
        lines.push("- All tracked asset categories meet the readiness threshold.".to_string());
    }

    lines.join("\n")
}

fn readiness_action_hint(item: &AgentReadinessItem) -> Option<String> {
    let label = item.label.as_str();
    Some(match item.check_name.as_str() {
        "mcp_enabled" => format!("Configure MCP servers for this project ({label})"),
        "skills_configured" => format!("Install or link Skills ({label})"),
        "prompt_files" => format!("Add project prompts or CLAUDE.md / AGENTS.md ({label})"),
        "commands_configured" => format!("Add slash commands ({label})"),
        "hooks_configured" => format!("Configure lifecycle hooks ({label})"),
        "ignore_rules" => format!("Set ignore rules ({label})"),
        "permissions" => format!("Review tool permissions ({label})"),
        "subagents_configured" => format!("Configure subagents ({label})"),
        "recent_updates" => {
            format!("Update project AI assets — none changed in ~90 days ({label})")
        }
        _ => format!("Improve {label}"),
    })
}

/// Write skill registry under `.opensunstar/` and gentle-ai compatible `.atl/`.
pub fn export_skill_registry(
    db: &Database,
    project_path: &str,
    target_app: Option<&str>,
) -> Result<PathBuf, AppError> {
    let root = PathBuf::from(project_path);
    if !root.is_dir() {
        return Err(AppError::Message(format!(
            "项目路径不存在或不是目录: {project_path}"
        )));
    }

    let mut rows = scan_project_skill_dirs(&root);
    rows.extend(linked_skills_from_db(db, &root, project_path, target_app)?);
    dedupe_registry_rows(&mut rows);

    let body = render_skill_registry(&rows);
    let primary = root.join(OPENSUNSTAR_DIR).join(REGISTRY_FILENAME);
    write_text_file(&primary, &body)?;

    let compat = root.join(ATL_COMPAT_DIR).join(REGISTRY_FILENAME);
    write_text_file(&compat, &body)?;

    Ok(primary)
}

fn scan_project_skill_dirs(project_root: &Path) -> Vec<RegistryRow> {
    let relative_roots = [
        "skills",
        ".claude/skills",
        ".cursor/skills",
        ".opencode/skills",
        ".agents/skills",
    ];

    let mut rows = Vec::new();
    for rel in relative_roots {
        let base = project_root.join(rel);
        if !base.is_dir() {
            continue;
        }
        collect_skill_md_under(&base, "project", &mut rows);
    }
    rows
}

fn collect_skill_md_under(base: &Path, scope: &'static str, rows: &mut Vec<RegistryRow>) {
    let Ok(entries) = fs::read_dir(base) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let skill_md = path.join("SKILL.md");
            if skill_md.is_file() {
                let dir_name = path
                    .file_name()
                    .map(|n| n.to_string_lossy().to_string())
                    .unwrap_or_default();
                let (name, description) = SkillService::read_skill_name_desc(&skill_md, &dir_name);
                rows.push(RegistryRow {
                    name,
                    description: description.unwrap_or_default(),
                    scope,
                    path: skill_md,
                });
            } else {
                collect_skill_md_under(&path, scope, rows);
            }
        }
    }
}

fn linked_skills_from_db(
    db: &Database,
    project_root: &Path,
    project_path: &str,
    target_app: Option<&str>,
) -> Result<Vec<RegistryRow>, AppError> {
    let Some(sqlite_id) = db.get_project_id_by_path(project_path)? else {
        return Ok(Vec::new());
    };

    let links = db.get_project_skills(&sqlite_id)?;
    let all_skills = db.get_all_installed_skills()?;
    let ssot_dir = SkillService::get_ssot_dir().map_err(|e| AppError::Message(e.to_string()))?;

    let app_filter = target_app.and_then(|a| AppType::from_str(a).ok());

    let mut rows = Vec::new();
    for link in links {
        if !link.enabled {
            continue;
        }
        let Some(skill) = all_skills.get(&link.config_id) else {
            continue;
        };
        if let Some(ref app) = app_filter {
            if !skill.apps.is_enabled_for(app) {
                continue;
            }
        }
        let skill_dir = ssot_dir.join(&skill.directory);
        let skill_md = skill_dir.join("SKILL.md");
        if !skill_md.is_file() {
            continue;
        }
        let (name, description) = SkillService::read_skill_name_desc(&skill_md, &skill.directory);
        rows.push(RegistryRow {
            name,
            description: description
                .unwrap_or_else(|| skill.description.clone().unwrap_or_default()),
            scope: "user",
            path: skill_md,
        });
    }

    // Also index project-local mirror if synced into repo (best-effort)
    let _ = project_root;
    Ok(rows)
}

fn dedupe_registry_rows(rows: &mut Vec<RegistryRow>) {
    let mut seen: HashMap<String, usize> = HashMap::new();
    let mut out = Vec::new();
    for row in rows.drain(..) {
        let key = row.name.to_lowercase();
        if seen.contains_key(&key) {
            // project scope wins over user
            if row.scope == "project" {
                if let Some(idx) = seen.get(&key).copied() {
                    out[idx] = row;
                }
            }
            continue;
        }
        seen.insert(key.clone(), out.len());
        out.push(row);
    }
    *rows = out;
}

fn render_skill_registry(rows: &[RegistryRow]) -> String {
    let mut lines = vec![
        "# Skill Registry".to_string(),
        String::new(),
        "> Index-only catalog generated by OpenSunstar. Load exact `SKILL.md` paths — do not summarize.".to_string(),
        String::new(),
        "| Skill | Trigger / description | Scope | Path |".to_string(),
        "| --- | --- | --- | --- |".to_string(),
    ];

    if rows.is_empty() {
        lines.push("| _none_ | No skills indexed for this project yet | — | — |".to_string());
    } else {
        for row in rows {
            let desc = row.description.replace('\n', " ").replace('|', "\\|");
            let path = row.path.display().to_string().replace('|', "\\|");
            lines.push(format!(
                "| {} | {} | {} | {} |",
                row.name.replace('|', "\\|"),
                desc,
                row.scope,
                path
            ));
        }
    }

    lines.join("\n")
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct BaselineAssetEntry {
    id: String,
    enabled: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    app_type: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct BaselineReadinessSummary {
    score: Option<u32>,
    max_score: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    evaluated_at: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    target_app: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BaselineSnapshot {
    pub version: u32,
    pub exported_at: i64,
    pub project_id: String,
    pub project_path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target_app: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blueprint_id: Option<String>,
    pub readiness: BaselineReadinessSummary,
    pub assets: BaselineSnapshotAssets,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct BaselineSnapshotAssets {
    pub mcp: Vec<BaselineAssetEntry>,
    pub skills: Vec<BaselineAssetEntry>,
    pub prompts: Vec<BaselineAssetEntry>,
    pub commands: Vec<BaselineAssetEntry>,
    pub hooks: Vec<BaselineAssetEntry>,
    pub ignore: Vec<BaselineAssetEntry>,
    pub permissions: Vec<BaselineAssetEntry>,
    pub subagents: Vec<BaselineAssetEntry>,
}

fn collect_baseline_assets(
    db: &Database,
    project_id: &str,
) -> Result<BaselineSnapshotAssets, AppError> {
    let mut assets = BaselineSnapshotAssets::default();

    for link in db.get_project_mcp_servers(project_id)? {
        assets.mcp.push(BaselineAssetEntry {
            id: link.config_id,
            enabled: link.enabled,
            app_type: None,
        });
    }
    for link in db.get_project_skills(project_id)? {
        assets.skills.push(BaselineAssetEntry {
            id: link.config_id,
            enabled: link.enabled,
            app_type: None,
        });
    }
    for link in db.get_project_prompts(project_id)? {
        assets.prompts.push(BaselineAssetEntry {
            id: link.prompt_id,
            enabled: link.enabled,
            app_type: Some(link.prompt_app_type),
        });
    }
    for asset_type in ["command", "hook", "ignore", "permission", "subagent"] {
        let links = db.get_project_asset_links(project_id, Some(asset_type))?;
        let target = match asset_type {
            "command" => &mut assets.commands,
            "hook" => &mut assets.hooks,
            "ignore" => &mut assets.ignore,
            "permission" => &mut assets.permissions,
            "subagent" => &mut assets.subagents,
            _ => unreachable!(),
        };
        for link in links {
            target.push(BaselineAssetEntry {
                id: link.asset_id,
                enabled: link.enabled,
                app_type: if link.asset_app_type.is_empty() {
                    None
                } else {
                    Some(link.asset_app_type)
                },
            });
        }
    }

    Ok(assets)
}

/// Write `.opensunstar/baseline-snapshot.json` (S2-03).
pub fn export_baseline_snapshot(
    db: &Database,
    project_id: &str,
    readiness: Option<&AgentReadinessResult>,
) -> Result<PathBuf, AppError> {
    let project = db
        .get_project(project_id)?
        .ok_or_else(|| AppError::Message(format!("项目不存在: {project_id}")))?;
    let root = PathBuf::from(&project.path);
    if !root.is_dir() {
        return Err(AppError::Message(format!(
            "项目路径不存在或不是目录: {}",
            project.path
        )));
    }

    let exported_at = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64;

    let readiness_summary = if let Some(r) = readiness {
        BaselineReadinessSummary {
            score: Some(r.score),
            max_score: r.max_score.max(AGENT_READINESS_MAX_SCORE),
            evaluated_at: r.evaluated_at,
            target_app: r.target_app.clone(),
        }
    } else {
        BaselineReadinessSummary {
            score: None,
            max_score: AGENT_READINESS_MAX_SCORE,
            evaluated_at: None,
            target_app: project.target_app.clone(),
        }
    };

    let snapshot = BaselineSnapshot {
        version: BASELINE_SNAPSHOT_VERSION,
        exported_at,
        project_id: project.id.clone(),
        project_path: project.path.clone(),
        target_app: project.target_app.clone(),
        blueprint_id: project.blueprint_id.clone(),
        readiness: readiness_summary,
        assets: collect_baseline_assets(db, project_id)?,
    };

    let out_path = root.join(OPENSUNSTAR_DIR).join(BASELINE_SNAPSHOT_FILENAME);
    let json = serde_json::to_string_pretty(&snapshot)
        .map_err(|e| AppError::Message(format!("序列化 baseline-snapshot 失败: {e}")))?;
    write_text_file(&out_path, &json)?;
    Ok(out_path)
}

pub fn refresh_baseline_snapshot_for_project_id(
    db: &Database,
    project_id: &str,
    readiness: Option<&AgentReadinessResult>,
) {
    let Ok(Some(project)) = db.get_project(project_id) else {
        return;
    };
    if !project_workspace_exists(&project.path) {
        log::debug!(
            "跳过 baseline-snapshot 导出：项目路径不可用 ({})",
            project.path
        );
        return;
    }
    if let Err(e) = export_baseline_snapshot(db, project_id, readiness) {
        log::warn!("导出 baseline-snapshot 失败 ({project_id}): {e}");
    }
}

/// 项目资产配置变更后的统一治理刷新（readiness 失效、写回、快照、registry）。
pub fn touch_project_governance(state: &crate::store::AppState, project_id: &str) {
    crate::ai::readiness_cache::invalidate_agent_readiness_for_project(&state.db, project_id, None);
    refresh_skill_registry_for_project_id(&state.db, project_id);
    let path_ok = state
        .db
        .get_project(project_id)
        .ok()
        .flatten()
        .map(|p| project_workspace_exists(&p.path))
        .unwrap_or(false);
    if path_ok {
        if let Err(e) =
            crate::services::project_config_sync::sync_all_for_project_id(state, project_id)
        {
            log::warn!("项目级配置写回失败 ({project_id}): {e}");
        }
    } else if let Ok(Some(project)) = state.db.get_project(project_id) {
        log::debug!("跳过项目级配置写回：项目路径不可用 ({})", project.path);
    }
    refresh_baseline_snapshot_for_project_id(&state.db, project_id, None);
}

/// Refresh skill registry files for a project known by SQLite id.
pub fn refresh_skill_registry_for_project_id(db: &Database, project_id: &str) {
    let Ok(Some(project)) = db.get_project(project_id) else {
        return;
    };
    if !project_workspace_exists(&project.path) {
        log::debug!(
            "跳过 skill-registry 导出：项目路径不可用 ({})",
            project.path
        );
        return;
    }
    if let Err(e) = export_skill_registry(db, &project.path, None) {
        log::warn!("导出项目 skill-registry 失败 ({}): {e}", project.path);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ai::types::AgentReadinessItem;

    #[test]
    fn renders_hints_with_gaps() {
        let result = AgentReadinessResult {
            score: 40,
            max_score: 100,
            details: vec![AgentReadinessItem {
                check_name: "mcp_enabled".to_string(),
                label: "MCP".to_string(),
                weight: 20,
                score: 0,
                detail: "missing".to_string(),
                status: Some("missing".to_string()),
                configured_state: None,
                effective_state: None,
                effective_detail: None,
                effective_scanned_at: None,
                live_path: None,
            }],
            llm_suggestion: None,
            is_cached: false,
            evaluated_at: Some(1),
            target_app: Some("claude".to_string()),
        };
        let md = render_agent_context_hints(&result);
        assert!(md.contains("Agent Context Hints"));
        assert!(md.contains("Configure MCP"));
    }

    #[test]
    fn not_required_items_do_not_generate_configuration_actions() {
        let result = AgentReadinessResult {
            score: 0,
            max_score: 100,
            details: vec![AgentReadinessItem {
                check_name: "mcp_enabled".to_string(),
                label: "MCP".to_string(),
                weight: 15,
                score: 0,
                detail: "unsupported".to_string(),
                status: Some("not_required".to_string()),
                configured_state: None,
                effective_state: None,
                effective_detail: None,
                effective_scanned_at: None,
                live_path: None,
            }],
            llm_suggestion: None,
            is_cached: false,
            evaluated_at: Some(1),
            target_app: Some("openclaw".to_string()),
        };

        let markdown = render_agent_context_hints(&result);

        assert!(!markdown.contains("Configure MCP"));
        assert!(markdown.contains("meet the readiness threshold"));
    }
}
